modLoader="javafml" #mandatory
loaderVersion="[25,)" #mandatory (25 is current forge version)
credits="Patmobile" #optional
authors="Patmobile" #optional

[[mods]] #mandatory
modId="paralleldimension" #mandatory
version="1.0.1" #mandatory
displayName="Parallel Dimension Mod" #mandatory
# The description text for the mod (multi line!) (#mandatory)
description='''
This is a multi-line description. 
This mod is awesome!
'''

# A dependency - use the . to indicate dependency for a specific modid. Dependencies are optional.
[[dependencies.paralleldimension]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[25,)" #mandatory
    ordering="NONE"
    side="BOTH"
	
# Here's another dependency
[[dependencies.paralleldimension]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.13.2]"
    ordering="NONE"
    side="BOTH"